### PR TITLE
add support for gdouble

### PR DESCRIPTION
**Pull request by martindemello**

### CODE REVIEW

**Comment by martindemello** [comment]
wasn't sure what sort of issues it could create to treat `gfloat` as an ocaml `float` too; if you feel it should be fine i can add that to this PR

**Comment by btj** [comment]
> wasn't sure what sort of issues it could create to treat `gfloat` as an ocaml `float` too; if you feel it should be fine i can add that to this PR

Possible loss of precision, but seems fine to add.

**Comment by martindemello** [comment]
okay, done. (i was mostly unsure how things would behave on 32 bit systems when trying to treat a c float as an ocaml float.)

**Comment by martindemello** [comment]
i do not understand the current CI test failure; it complains about `Gtk.picture` not having a `set_content_fit` method but i can see it in the generated `Gtk.ml` file and the test runs fine locally.

**Comment by martindemello** [comment]
ah, looks like the ubuntu sandbox installs an older version of gtk4 that lacks the method. replaced it with something else in the test.

**Comment by btj** [comment]
Are you sure the tests are being run by the CI workflow?

**Comment by martindemello** [comment]
no, i'm pretty sure they're not, i was just trying to get them to compile so the CI passed. i'll look up how to get `dune runtest` working with the github workflow and do that in a separate PR.

**Pull request merged**
