### PR TITLE
Dune

### PR DESCRIPTION
**Pull request by chris-armstrong**
I've been experimenting with the code that exists, and in order to get it working on Linux I've started putting together some changes:

* Replace Makefile with dune compilation
* Rename files for case-sensitive filesystems (Linux)
* Start adding a README.md
* Tweaked the generation a bit (you may wish to revert some of this like the removal of the underscores from some names, but in some cases I found it necessary on 4.08 definitions to remove variable name conflicts)

### CODE REVIEW

**Comment by btj** [comment]
Thanks!

However, the underscores were meant to reserve the non-underscored names for the OO layer. I elaborated the OO layer generation a bit to clarify what I mean. Otherwise, your code looks fine!

**Comment by btj** [comment]
The OO example now works

**Comment by btj** [comment]
Any chance you could set up a GitHub Actions build?

**Comment by chris-armstrong** [comment]
I've resolved the merge conflicts and added in the OO example to the dune file.

I'm not too familiar with GitHub Actions - could that be done in a separate PR? I'd need to assemble a Dockerfile to start with that installs gtk - I know the opam/opam images start with opam and have Ubuntu bases available, so that'd be the place to start.

**Pull request merged**
